### ISSUE TITLE
Cannot access Gallery while uploading Aadhar Card/PAN Card.

### ISSUE THREAD

**Issue by savitore** [Android-Ants/Fundon-App#8]
While uploading files like aadhar cards and pan cards, users are asked permission to access files, not pictures. Due to this, users are not able to upload images from the gallery.

**Comment by soCallmeAdityaKumar** [comment]
I would like to work on it

**Comment by savitore** [comment]
Sure, assigned to @soCallmeAdityaKumar

**Comment by AnshTandon0** [comment]
Assigned to @soCallmeAdityaKumar

**Comment by AnshTandon0** [comment]
Completed by @soCallmeAdityaKumar
